### ISSUE TITLE
@mdi/js out of sync with materialdesngicons.com

### ISSUE THREAD

**Issue by therufa** [Templarian/MaterialDesign-JS#9]
Hi, one of my [peers recently noticed](https://github.com/therufa/mdi-vue/issues/39) that materialdesignicons.com does have some icons, which are not contained inside the icon lib I maintain. After a quick look, I realized that `@mdi/js` was published almost a month ago.
Could you make an update?

**Comment by Templarian** [comment]
@therufa The team has refocused this release into the new website after doing two large releases in a row last month.

For now define a `const mdiIconName = 'path data from site';`

A release bump for 3.4.xx will not be for a bit due to priority shift. Closing this issue as all packages get bumped at the same time.

**Comment by simondoescode** [comment]
+1 to add this to the roadmap.

**Comment by Templarian** [comment]
@SimonFricker Right now we only have 27 icons in the next release bucket out of 5k. This unfortunately is enough for us to do a release, but we have a lot of pending icons, so we can cut a release at 50. 👍
